DOSA_keys/urls.py
from django.conf.urls import include, url
from loads.views import com_settings

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/settings/', com_settings, name='settings'),
    url(r'^admin/', include('local_admin.urls')),
    url(r'^user/', include('users.urls')),
    ]

local_admin/urls.py
from django.conf.urls import url
from .views import dosing, \
    cistern_add, cistern_list, cistern_edit, cistern_info, \
    add_fuel, fuels_list, fuel_info,\
    keys, edit_key, \
    users, add_local_user, edit_local_user, \
    hide_admin


urlpatterns = [
    url(r'^$', dosing, name='dosing'),
    url(r'^cisterns/$', cistern_list, name='cistern_list'),
    url(r'^cisterns/add-cistern/$', cistern_add, name='cistern_add'),
    url(r'^cisterns/edit/(?P<cist_id>\d+)/', cistern_edit, name='cist_edit'),
    url(r'^cisterns/(?P<cist_id>\d+)/', cistern_info, name='cist_info'),
    url(r'^fuels/$', fuels_list, name='fuels'),
    url(r'^fuels/add-fuel/$', add_fuel, name='add_fuel'),
    url(r'^fuels/(?P<fuel_id>\d+)/', fuel_info, name='fuel_info'),
    url(r'^keys/$', keys, name='keys'),
    url(r'^keys/edit/(?P<key_id>\d+)/', edit_key, name='edit_key'),
    url(r'^users/$', users, name='users'),
    url(r'^users/add-user/$', add_local_user, name='add_user'),
    url(r'^users/edit/(?P<user_id>\d+)/', edit_local_user, name='edit_user'),
    url(r'^hide-admin/$', hide_admin, name='hide_admin'),
    ]

main/urls.py
from django.conf.urls import url
from .views import login_user, logout_user, change_user_passwd, licence_key

urlpatterns = [
    url(r'^$', login_user, name='login'),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^change-password/$', change_user_passwd, name='change-pwd'),
    url(r'^licence/$', licence_key, name='activation'),
]

users/urls.py
from django.conf.urls import url
from .views import dosing, cistern_list, cistern_info, keys, fuel_info

urlpatterns = [
    url(r'^$', dosing, name='dosing'),
    url(r'^cisterns/$', cistern_list, name='cistern_list'),
    url(r'^cisterns/(?P<cist_id>\d+)/', cistern_info, name='cist_info'),
    url(r'^keys/$', keys, name='keys'),
    url(r'^fuels/(?P<fuel_id>\d+)/', fuel_info, name='fuel_info'),
]

loads/models.py
from django.db import models
from django.contrib.auth.models import User


# Тип топлива
class FuelType(models.Model):
    name = models.CharField(max_length=40, unique=True)
    comment = models.TextField(null=True, blank=True)


# Резервуар
class Cistern(models.Model):
    CISTERN_TYPES = (('box', 'куб'),
                     ('hc', 'горизонтальный цилиндр'),
                     ('vc', 'вертикальный цилиндр'))
    start_volume = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    max_volume = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    cistern_type = models.CharField(max_length=3, choices=CISTERN_TYPES)
    fuel = models.ForeignKey(FuelType)
    name = models.CharField(max_length=20, default='')

    def save(self, *args, **kwargs):
        if self.start_volume > self.max_volume:
            raise ValueError('Начальное значение не может превышать максимальное')
        else:
            super(Cistern, self).save(*args, **kwargs)


# БД Ключей
class KeyOwner(models.Model):
    name = models.CharField(max_length=40, default='')
    car = models.CharField(max_length=40, default='')
    keys = models.CharField(max_length=16, unique=True)
    comment = models.TextField(null=True, blank=True)
    cistern = models.ForeignKey(Cistern, null=True, blank=True)


# БД Отгрузок
class Database(models.Model):
    user = models.ForeignKey(KeyOwner)
    op_id = models.CharField(max_length=20)
    dosed = models.DecimalField(decimal_places=2, max_digits=15)
    date_time = models.DateTimeField()
    add = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    cistern_volume = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    fuel_volume = models.DecimalField(decimal_places=2, max_digits=15, default=0)
    delete = models.BooleanField(default=False)

    class Meta:
        ordering = ["date_time"]


# БД Загрузок
class UpDosed(models.Model):
    user = models.ForeignKey(User)
    cistern = models.ForeignKey(Cistern)
    date_time = models.DateTimeField()
    volume = models.DecimalField(decimal_places=2, max_digits=15)
    comment = models.TextField(null=True, blank=True)


# Параметры соединения
class Connect(models.Model):
    port = models.CharField(max_length=20, default='0')
    speed = models.PositiveIntegerField(default=115200)


class Licenced(models.Model):
    date_time = models.DateField()
    trial = models.BooleanField(default=True)

loads/forms.py
from django import forms


class DateFilter(forms.Form):
    start_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker form-control',
                                                               'placeholder': 'с даты'}),
                                 input_formats=('%d.%m.%Y', '%Y-%m-%d'), required=False)
    end_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker form-control',
                                                             'placeholder': 'по дату'}),
                               input_formats=('%d.%m.%Y', '%Y-%m-%d'), required=False)


class UserFilter(forms.Form):
    filter_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': 30,
                                                                'placeholder': 'имя'}),
                                  max_length=30, required=False)
    filter_car = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': 40,
                                                               'placeholder': 'машина'}),
                                 max_length=40, required=False)


class FuelFilter(forms.Form):
    filter_fuel = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': 30,
                                                                'placeholder': 'топливо'}),
                                  max_length=30, required=False)


class AddKeysForm(forms.Form):
    key_file = forms.FileField(label='', widget=forms.ClearableFileInput(attrs={'required': True}))

local_admin/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.forms.formsets import BaseFormSet

from loads.models import KeyOwner, Cistern


class EditKeyOwnerForm(ModelForm):
    class Meta:
        model = KeyOwner
        fields = {'name', 'car', 'keys', 'comment'}
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 40}),
                   'car': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 40}),
                   'keys': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 16}),
                   'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'cols': 50})}


class AddSystemUserForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                               'required': True, 'maxlength': 30}),
                                 max_length=30)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'required': True, 'maxlength': 30}),
                                max_length=30)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'required': True}))


class EditDjangoUserForm(ModelForm):
    class Meta:
        model = User
        fields = {'first_name', 'last_name', 'email'}
        widgets = {'first_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'last_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'email': forms.EmailInput(attrs={'class': 'form-control'})}


class CisternForm(ModelForm):
    class Meta:
        model = Cistern
        fields = {'start_volume', 'max_volume', 'cistern_type', 'name'}
        widgets = {'start_volume': forms.NumberInput(attrs={'class': 'form-control'}),
                   'max_volume': forms.NumberInput(attrs={'class': 'form-control'}),
                   'cistern_type': forms.Select(attrs={'class': 'form-control'}),
                   'name': forms.TextInput(attrs={'class': 'form-control'})}


class AddUpDosedForm(forms.Form):
    volume = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
                                max_digits=7, decimal_places=2, min_value=0.0)
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)


class FuelForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'maxlength': 40,
                                                         'placeholder': 'Тип'}),
                           max_length=40)
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Комментарий', 'rows': 2}),
                              required=False)


class BaseFuelFormSet(BaseFormSet):
    def clean(self):
        if any(self.errors):
            return
        types = []
        duplicates = False
        for form in self.forms:
            if form.cleaned_data:
                name = form.cleaned_data['name']
                if name in types:
                    duplicates = True
                types.append(name)
                if duplicates:
                    raise forms.ValidationError(
                        'Типы топлива должны быть уникальны',
                        code='duplicate_types'
                    )

templates/local_admin/cistern_add.html
{% extends 'base.html' %}

{% block title %}
    <title>Добавление резервуара</title>
{% endblock %}

{% block navbar-header %}
    <a class="navbar-brand">Администратор DOSA</a>
{% endblock %}

{% block navigation %}
    <!-- Определение активной вкладки -->
    <li><a href="/admin/">Отгрузки</a></li>
    <li><a href="/admin/cisterns/">Резервуары</a></li>
    <li><a href="/admin/fuels/">Топливо</a></li>
    <li><a href="/admin/keys/">Ключи</a></li>
    <li><a href="/admin/users/">Пользователи</a></li>
{% endblock %}

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
    {% if add_cist.non_field_errors %}
        {% for error in add_cist.non_field_errors %}
            <div class="alert alert-danger">
                <a class="close" data-dismiss="alert">×</a>
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    {% for field in add_cist %}
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <a class="close" data-dismiss="alert">×</a>
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}
    {% endfor %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default panel-my">
            <div class="panel-heading panel-heading-my"><h4>Добавление резервуара</h4></div>
            <div class="jumbotron">
                <form method="post" class="form-horizontal"> {% csrf_token %}
                    <div class="form-group">
                        {% load widget_tweaks %}
                        <label for="id_cistern_name" class="col-sm-4 control-label">Имя резервуара:</label>
                        <div class="col-sm-6">{{ add_cist.name|attr:'required:true' }}</div>
                        <label for="id_start_volume" class="col-sm-4 control-label">Начальный объем:</label>
                        <div class="col-sm-6" >{{ add_cist.start_volume|attr:'required:true' }}</div>
                        <label for="id_max_volume" class="col-sm-4 control-label">Максимальный объем:</label>
                        <div class="col-sm-6">{{ add_cist.max_volume|attr:'required:true' }}</div>
                        <label for="id_cistern_type" class="col-sm-4 control-label">Тип резервуара:</label>
                        <div class="col-sm-6">{{ add_cist.cistern_type|attr:'required:true' }}</div>
                        <label for="id_fuel" class="col-sm-4 control-label">Тип топлива:</label>
                        <div class="col-sm-6">
                            <select name="select_fuel" id="id_fuel" class="form-control" required>
                                {% for fuel in fuel_types %}
                                    <option value="{{ fuel.name }}">{{ fuel.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <label for="id_keys" class="col-sm-4 control-label">Ключи:</label>
                        <div class="col-sm-6">
                            <select name="keys" size="4" multiple id="id_keys" class="form-control" required>
                                {% for entry in keys %}
                                    <option>{{ entry.keys }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 col-md-offset-9">
                            <button class="btn btn-block btn-lg btn-file" type="submit">Добавить</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/local_admin/cistern_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Редактирование резервуара</title>
{% endblock %}

{% block navbar-header %}
    <a class="navbar-brand">Администратор DOSA</a>
{% endblock %}

{% block navigation %}
    <!-- Определение активной вкладки -->
    <li><a href="/admin/">Отгрузки</a></li>
    <li><a href="/admin/cisterns/">Резервуары</a></li>
    <li><a href="/admin/fuels/">Топливо</a></li>
    <li><a href="/admin/keys/">Ключи</a></li>
    <li><a href="/admin/users/">Пользователи</a></li>
{% endblock %}

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
    {% if edit_cist.non_field_errors %}
        {% for error in edit_cist.non_field_errors %}
            <div class="alert alert-danger">
                <a class="close" data-dismiss="alert">×</a>
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    {% for field in edit_cist %}
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <a class="close" data-dismiss="alert">×</a>
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}
    {% endfor %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default panel-my">
            <div class="panel-heading panel-heading-my"><h4>Редактирование резервуара</h4></div>
            <div class="jumbotron">
                <form method="post" class="form-horizontal"> {% csrf_token %}
                    <div class="form-group">
                        <label for="id_cistern_name" class="col-sm-4 control-label">Имя резервуара:</label>
                        <div class="col-sm-6">{{ edit_cist.name }}</div>
                        <label for="id_start_volume" class="col-sm-4 control-label">Начальный объем:</label>
                        <div class="col-sm-6" >{{ edit_cist.start_volume }}</div>
                        <label for="id_max_volume" class="col-sm-4 control-label">Максимальный объем:</label>
                        <div class="col-sm-6">{{ edit_cist.max_volume }}</div>
                        <label for="id_cistern_type" class="col-sm-4 control-label">Тип резервуара:</label>
                        <div class="col-sm-6">{{ edit_cist.cistern_type }}</div>
                        <label for="id_fuel" class="col-sm-4 control-label">Тип топлива:</label>
                        <div class="col-sm-6">
                            {% if fuel_types %}
                                <select name="select_fuel" id="id_fuel" class="form-control">
                                    <option value="{{ cur_fuel }}">{{ cur_fuel }}</option>
                                    {% for fuel in fuel_types %}
                                        <option value="{{ fuel.name }}">{{ fuel.name }}</option>
                                    {% endfor %}
                                </select>
                            {% else %}
                                <select name="select_line" id="id_fuel" class="form-control" disabled>
                                    <option value="{{ cur_fuel }}">{{ cur_fuel }}</option>
                                </select>
                            {% endif %}
                        </div>
                        <label for="id_sel" class="col-sm-4 control-label">Ключи:</label>
                        <div class="col-sm-6 form-inline">
                            <select id="id_sel" name="keys" multiple class="form-control" style="float: left;" size="4" required>
                                {% for entry in selected %}
                                    <option selected>{{ entry.keys }}</option>
                                {% endfor %}
                                {% for entry in can_select %}
                                    <option>{{ entry.keys }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 col-md-offset-9">
                            <button id="send" class="btn btn-block btn-lg btn-file" type="submit">Редактировать</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/local_admin/dosing.html
{% extends 'base.html' %}

{% block title %}
    <title>Перечень отгрузок</title>
{% endblock %}

{% block navbar-header %}
    <a class="navbar-brand">Администратор DOSA</a>
{% endblock %}

{% block head %}
    <style type="text/css">
        #id_start_date, #id_end_date{
            max-width: 135px;
        }
    </style>
{% endblock %}

{% block navigation %}
    <!-- Определение активной вкладки -->
    <li class="active"><a href="/admin/">Отгрузки</a></li>
    <li><a href="/admin/cisterns/">Резервуары</a></li>
    <li><a href="/admin/fuels/">Топливо</a></li>
    <li><a href="/admin/keys/">Ключи</a></li>
    <li><a href="/admin/users/">Пользователи</a></li>
{% endblock %}

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default panel-my">
            <div class="panel-heading panel-heading-my clearfix">
                <form method="get" class="form-inline navbar-form navbar-left" style="padding-left: 0;"> {% csrf_token %}
                    <label for="id_filter_name" class="sr-only">имени</label>
                    {{ user_filter.filter_name }}
                    <label for="id_filter_car" class="sr-only">машине</label>
                    {{ user_filter.filter_car }}
                    <label for="id_filter_fuel" class="sr-only">типу жидкости</label>
                    {{ fuel_filter.filter_fuel }}
                    <label for="id_start_date_picker" class="sr-only">дате с</label>
                    {{ date_filter.start_date }}
                    <label for="id_end_date_picker" class="sr-only">по</label>
                    {{ date_filter.end_date }}
                    <input type="hidden" name="db_page" id="id_db_page"/>
                    <button class="btn btn-default" type="submit" title="Фильтровать" id="filter">
                        <span class="glyphicon glyphicon-filter"></span>
                    </button>
                    <a href="/admin/" class="btn btn-default" title="Сбросить фильтры">
                        <span class="glyphicon glyphicon-remove-circle"></span>
                    </a>
                    <button class="btn btn-success" name="to_xls" value=1 type="submit" title="Экспорт в Excel">
                        <span class="glyphicon glyphicon-list-alt"></span>
                    </button>
                    <button class="btn btn-warning" id="trash" name="delete" value=1 type="submit" title="Удалить записи">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
                <ul class="navbar-right navbar-nav nav" style="padding-top: 10px; padding-right: 5px;">
                    <li>
                        <div>
                            <a href="/admin/settings/" class="btn btn-primary glyphicon glyphicon-cog" title="Настроить порт"></a>
                        </div>
                    </li>
                    <li>
                        <form method="get" style="padding-left: 2px;"> {% csrf_token %}
                            <button class="btn btn-primary" name="refr_log" value=1 type="submit" title="Обновить БД">
                                <span class="glyphicon glyphicon-refresh"></span>
                            </button>
                        </form>
                    </li>
                </ul>
            </div>
            <!-- Таблица отгрузок -->
            <div>
                <table class="local_user_table table table-striped" id="db_table">
                    <thead>
                        <tr>
			                <th class="col-sm-1" style="text-align: center; vertical-align: middle;">#</th>
			                <th style="vertical-align: middle;">Имя</th>
			                <th style="vertical-align: middle;">Машина</th>
                            <th style="vertical-align: middle;">Резервуар</th>
                            <th style="vertical-align: middle;">Топливо</th>
			                <th style="text-align: center; vertical-align: middle;">Ключ</th>
			                <th>Отгружено</th>
			                <th style="text-align: center;">Дата</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for entry in db %}
                            <tr>
                                <td style="text-align: center;">{{ forloop.counter0|add:db.start_index }}</td>
                                <td>
                                    {% if entry.user.name %}
                                        {{ entry.user.name }}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if entry.user.car %}
                                        {{ entry.user.car }}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if entry.user.cistern %}
                                        <a href="/admin/cisterns/{{ entry.user.cistern.id }}">
                                            {{ entry.user.cistern.name }}
                                        </a>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if entry.user.cistern %}
                                        <a href="/admin/fuels/{{ entry.user.cistern.fuel.id }}">
                                            {{ entry.user.cistern.fuel.name }}
                                        </a>
                                    {% endif %}
                                </td>
                                <td style="text-align: center;">{{ entry.user.keys }}</td>
                                <td>{{ entry.dosed }}</td>
                                <td style="text-align: center;">{{ entry.date_time|date:'d.m.Y H:i' }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <nav aria-label="Page navigation" style="text-align: center;">
                    <ul class="pagination">
                        {% if db.has_previous %}
                            <li>
                                <a title="1" id="1"
                                   onclick="pag(this, 'id_db_page')">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            <li>
                                <a id="{{ db.previous_page_number }}"
                                   onclick="pag(this, 'id_db_page')"
                                   title="{{ db.previous_page_number }}">
                                    <span aria-hidden="true">&lsaquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <span aria-hidden="true">&laquo;</span>
                            </li>
                            <li class="disabled">
                                <span aria-hidden="true">&lsaquo;</span>
                            </li>
                        {% endif %}
                        <li class="disabled">
                            <a href="?db_page={{ db.number }}">
                                {{ db.number }}
                            </a>
                        </li>
                        {% if db.has_next %}
                            <li>
                                <a id="{{ db.next_page_number }}"
                                   onclick="pag(this, 'id_db_page')"
                                   title="{{ db.next_page_number }}">
                                    <span aria-hidden="true">&rsaquo;</span>
                                </a>
                            </li>
                            <li>
                                <a id="{{ db.paginator.num_pages }}"
                                   onclick="pag(this, 'id_db_page')"
                                   title="{{ db.paginator.num_pages }}">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <span aria-hidden="true">&rsaquo;</span>
                            </li>
                            <li class="disabled">
                                <span aria-hidden="true">&raquo;</span>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $("#db_table").tablesorter({
                 dateFormat : "ddmmyyyy",
                headers: {
                    7: {sorter: "shortDate"}
                }
            });
            $('.form-control').click(function(){
                $(this).val('')
            });
            jQuery.datetimepicker.setLocale('ru');
            $(".datepicker").datetimepicker({
                timepicker:false,
                format:'d.m.Y'
            });
        });
    </script>
{% endblock %}

templates/local_admin/key_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Редактирование ключа</title>
{% endblock %}

{% block navbar-header %}
    <a class="navbar-brand">Администратор DOSA</a>
{% endblock %}

{% block navigation %}
    <!-- Определение активной вкладки -->
    <li><a href="/admin/">Отгрузки</a></li>
    <li><a href="/admin/cisterns/">Резервуары</a></li>
    <li><a href="/admin/fuels/">Топливо</a></li>
    <li><a href="/admin/keys/">Ключи</a></li>
    <li><a href="/admin/users/">Пользователи</a></li>
{% endblock %}

{% block messages %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                <a class="close" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}
    {% if edit_form.non_field_errors %}
        {% for error in edit_form.non_field_errors %}
            <div class="alert alert-danger">
                <a class="close" data-dismiss="alert">×</a>
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    {% for field in edit_form %}
        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <a class="close" data-dismiss="alert">×</a>
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}
    {% endfor %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default panel-my">
            <div class="panel-heading panel-heading-my"><h4>Редактирование владельца ключа</h4></div>
            <div class="jumbotron">
                <form method="post" class="form-horizontal"> {% csrf_token %}
                    <div class="form-group">
                        {% load widget_tweaks %}
                        <label for="id__name" class="col-sm-3 control-label">Имя:</label>
                        <div class="col-sm-7">{{ edit_form.name }}</div>
                        <label for="id_car" class="col-sm-3 control-label">Машина:</label>
                        <div class="col-sm-7">{{ edit_form.car }}</div>
                        <label for="id_keys" class="col-sm-3 control-label">Ключ:</label>
                        <div class="col-sm-7">{{ edit_form.keys|attr:'readonly' }}</div>
                        <label for="id_comment" class="col-sm-3 control-label">Комментарий:</label>
                        <div class="col-sm-7">{{ edit_form.comment }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 col-md-offset-9">
                            <button class="btn btn-block btn-lg btn-file" type="submit">Редактировать</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}